In [1]:
%%timeit
import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 5)  
        self.fc2 = nn.Linear(5, 1)   

    def forward(self, x):
        x = F.relu(self.fc1(x))      
        x = torch.sigmoid(self.fc2(x))  
        return x


model = SimpleNN()

dummy_input = torch.randn(1, 10)  

output = model(dummy_input)

print(output)  


tensor([[0.5098]], grad_fn=<SigmoidBackward0>)
tensor([[0.3959]], grad_fn=<SigmoidBackward0>)
tensor([[0.5650]], grad_fn=<SigmoidBackward0>)
tensor([[0.5760]], grad_fn=<SigmoidBackward0>)
tensor([[0.7314]], grad_fn=<SigmoidBackward0>)
tensor([[0.6175]], grad_fn=<SigmoidBackward0>)
tensor([[0.3568]], grad_fn=<SigmoidBackward0>)
tensor([[0.4921]], grad_fn=<SigmoidBackward0>)
249 µs ± 125 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
